// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW8VxjKv0-exMeZXjnS6pRK7lAKRTnTic',
    appId: '1:902797635993:android:626ac477aec8a60a26e308',
    messagingSenderId: '902797635993',
    projectId: 'siagatani-ea8a5',
    storageBucket: 'siagatani-ea8a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6f3lzUIEVhh06X8r3nvde1K-ZMr_-1hE',
    appId: '1:902797635993:ios:276fd0990231160e26e308',
    messagingSenderId: '902797635993',
    projectId: 'siagatani-ea8a5',
    storageBucket: 'siagatani-ea8a5.firebasestorage.app',
    androidClientId: '902797635993-cco8686rmstaslrc483qf8rg57qi06gt.apps.googleusercontent.com',
    iosClientId: '902797635993-790voddnq5105e0s69lk3uu27f332ha9.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamFiveFe',
  );
}
