name: Code Quality Checks

on:
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'docs/**'
      - 'mock_server/**'

jobs:
  quality_check:
    name: Analyze and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Check Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze Code
        run: flutter analyze

      - name: Run Tests
        run: flutter test